### ISSUE TITLE
/src/jffs2/sunjffs2.c - modprobe?

### ISSUE THREAD

**Issue by markcoker** [cinquemb/firmware-mod-kit-osx#7]
sh: modprobe: command not found
sh: modprobe: command not found
sh: modprobe: command not found
sh: modprobe: command not found
sh: rmmod: command not found
sh: modprobe: command not found
dd: /dev/mtdblock1: Device not configured
mount: exec /Library/Filesystems/jffs2.fs/Contents/Resources/mount_jffs2 for [file directory]/jffs2-root: No such file or directory
cp: jffs2-root/*: No such file or directory
umount: jffs2-root: not currently mounted

**Comment by cinquemb** [comment]
https://en.m.wikipedia.org/wiki/Modprobe

**Comment by markcoker** [comment]
i thought this was modded for mac OS X?

**Comment by cinquemb** [comment]
I didn't port everything, just what I wanted to use.
