### ISSUE TITLE
Error : no lzma related files

### ISSUE THREAD

**Issue by tkhwang** [cinquemb/firmware-mod-kit-osx#8]
During configuring, it failed due to the lack of lzma related files.
But I don't know how to get those files.

```bash
checking lzma.h usability... no
checking lzma.h presence... no
checking for lzma.h... no
error: missing liblzma header files
```

Could you let me know?

Thanks,
tkhwang

**Comment by cinquemb** [comment]
Yeah, you need to install liblzma. You can use this, or any other way you see fit http://tukaani.org/xz/

**Comment by drewbug** [comment]
@cinquemb Would you mind giving a hint as to how you got liblzma installed? `brew install xz` doesn't seem to be sufficient.

**Comment by cinquemb** [comment]
download the source from link in the above comment, and follow the instructions in INSTALL

**Comment by camdenorrb** [comment]
brew worked for me btw

**Comment by Jonnaz** [comment]
I couldn't get brew xz lzma to work, however I added /usr/local/include to the environmental variables

export CPPFLAGS='-I/usr/local/include'

Then it started working.

I know this thread is old but it has a high rank on google for this error and thought it may help others in time to come.
